#Validaciones de las clases bajo el directorio Entity
Salita\PacienteBundle\Entity\Paciente:
    properties:
        tipoDocumento:
            - NotNull: ~
        nroDoc:
            - NotBlank: ~
            - Regex:
                pattern: "/^([0-9])*$/"
                match:   true
                message: El numero de documento no puede contener letras.
        nombre:
            - NotBlank: ~
            - Regex:
                pattern: "/\d/"
                match:   false
                message: El nombre no puede contener numeros.
        apellido:
            - NotBlank: ~
            - Regex:
                pattern: "/\d/"
                match:   false
                message: El apellido no puede contener numeros.
        telefonoFijo:
            - Regex:
                pattern: "/^([0-9])*$/"
                match:   true
                message: El telefono fijo no puede contener letras.
        telefonoMovil:
            - Regex:
                pattern: "/^([0-9])*$/"
                match:   true
                message: El telefono movil no puede contener letras
        calle:
            - NotBlank:
                message: Complete este campo por favor.
        numero:
            - NotBlank:
                message: Complete este campo por favor.
        pais:
            - NotNull: ~
        barrio:
            - NotNull: ~
        localidad:
            - NotNull: ~
        partido:
            - NotNull: ~
        sexo:
            - NotNull: ~
            
Salita\PacienteBundle\Entity\AntecedentePersonalObstetrico:
    properties:
        gestasPrevias:
            - Regex:
                pattern: "/^([0-9])*$/"
                match:   true
                message: La cantidad de gestas previas no puede contener letras.
        abortos:
            - Regex:
                pattern: "/^([0-9])*$/"
                match:   true
                message: La cantidad de abortos no puede contener letras.
        cesareas:
            - Regex:
                pattern: "/^([0-9])*$/"
                match:   true
                message: La cantidad de cesáreas no puede contener letras.        
        partos:
            - Regex:
                pattern: "/^([0-9])*$/"
                match:   true
                message: La cantidad de partos no puede contener letras.
                
Salita\PacienteBundle\Entity\Estudio:
    properties:
        resultado:
            - NotBlank:
                message: Complete este campo por favor.
        nroProtocolo:
            - NotBlank:
                message: Complete este campo por favor.
                
#Validaciones de las clases bajo el directorio Clases
Salita\PacienteBundle\Clases\Busqueda:
    properties:
        palabra:
            - NotBlank:
                message: Complete este campo por favor.