#Validaciones de las clases bajo el directorio Entity
Salita\UsuarioBundle\Entity\Usuario:
    properties:
        nombre:
            - NotBlank:
                message: Complete este campo por favor.
        apellido:
            - NotBlank:
                message: Complete este campo por favor.
        telefono:
            - NotBlank:
                message: Complete este campo por favor.