parameters:
    repos_manager.class: Salita\OtrosBundle\Service\ReposManager
    session_manager.class: Salita\OtrosBundle\Service\SessionManager
    dialogs_manager.class: Salita\OtrosBundle\Service\DialogsManager
    queries_manager.class: Salita\OtrosBundle\Service\QueriesManager
    persistence_manager.class: Salita\OtrosBundle\Service\PersistenceManager
    
#    salita_otros.example.class: Salita\OtrosBundle\Example

services:
    repos_manager:
        class: %repos_manager.class%
        arguments: [@doctrine.orm.entity_manager]
    session_manager:
        class: %session_manager.class%
        arguments: [@session]
    dialogs_manager:
        class: %dialogs_manager.class%
    queries_manager:
        class: %queries_manager.class%
        arguments: [@repos_manager]
    persistence_manager:
        class: %persistence_manager.class%
        arguments: [@repos_manager]
        
        
#    salita_otros.example:
#        class: %salita_otros.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
