#Validaciones de las clases bajo el directorio Clases
Salita\OtrosBundle\Clases\Busqueda:
    properties:
        palabra:
            - NotBlank:
                message: "Debe ingresar la palabra de busqueda"
                
#Validaciones de las clases bajo el directorio Entity
Salita\OtrosBundle\Entity\Barrio:
    properties:
        nombre:
            - NotBlank:
                message: "Debe ingresar un nombre de barrio"
            - Length:
                min: 5
                max: 50
                minMessage: "El nombre no puede contener menos de {{ limit }} letras"
                maxMessage: "El nombre no puede contener mas de {{ limit }} letras"
        localidad:
            - NotNull:
                message: "Debe ingresar la localidad a la que pertenece el barrio"

Salita\OtrosBundle\Entity\MetodoEstudio:
    properties:
        nombre:
            - NotBlank:
                message: "Debe ingresar un nombre para el metodo de estudio"
            - Length:
                max: 50
                maxMessage: "El nombre no puede contener mas de {{ limit }} letras"

Salita\OtrosBundle\Entity\MetodoEstudio:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nombre
    properties:
        nombre:
            - NotBlank: ~