Salita\OtrosBundle\Entity\Barrio:
    properties:
        nombre:
            - Length:
                min: 5
                max: 10
                minMessage: "El nombre no puede contener menos de {{ limit }} letras"
                maxMessage: "El nombre no puede contener mas de {{ limit }} letras"
            - NotBlank:
                message: "Debe ingresar un nombre de barrio"

Salita\OtrosBundle\Entity\MetodoEstudio:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nombre
    properties:
        nombre:
            - NotBlank: ~
